### PR TITLE
Improvements for Windows

### PR DESCRIPTION
**Pull request by egabrum**
* Added parsing of net mask for Windows.
* Fixed default_interface for Windows
* Fixed test_command to make it compatible with both Linux and Windows.

### CODE REVIEW

**Comment by egabrum** [comment]
Somewhat related to issue #25

**Comment by egabrum** [comment]
pinging @ftao

**Comment by egabrum** [comment]
pinging @benjaoming

**Review by benjaoming — APPROVED** [review]
Thanks @egabrum!

Since this is a small change similar to other patterns, I don't see the big risk. If you want to make sure it stays correct, you should add a test for it, though, in  `tests/ ipconfig_tests.py `.

**Comment by benjaoming** [comment]
Hi @egabrum - it seems you added the tests but something went wrong when rebasing the PR?

**Pull request closed without merging**
