### PR TITLE
Updates from current PyPi release

### PR DESCRIPTION
**Pull request by benjaoming**
Released 0.10 on PyPi with these contents.

I'm not sure how you want to go about with this, but in case you have changes, I'm gonna merge them back and release them on pypi, after all this is the main repo :)

This also has tests, and they pass!

### CODE REVIEW

**Comment by benjaoming** [comment]
Argh, for the reasons stated here:

https://github.com/learningequality/python-ifcfg/issues/3

...the 0.10 release isn't quite good enough. Need to refactor the code to make it handle falling back to `ip address` more cleanly than it does right now. It's still failing on systems w/o `ifconfig` :(

**Comment by ftao** [comment]
Thanks . 

By the way , this is repo is also a fork , but it seems the original repo has been deleted by the original author .

**Comment by benjaoming** [comment]
Oh haha okay :)

Would you be interested in setting up a collaboration? It doesn't make much sense to have repo A with PyPi access and repo B as main repo.

Thinking that if you crown me with access to this repo, I can help merge stuff, bump versions etc..

Workflow-wise, I always go through PRs when others are involved, never pushing straight to master.

**Comment by ftao** [comment]
Sure . 
Just added you as collaborator.

**Comment by benjaoming** [comment]
Cheers! :)

Could you enable issue tracking on the repo?

**Comment by ftao** [comment]
Ok. 
It is enabled now .

**Pull request merged**
