### PR TITLE
Relase 0.21

### PR DESCRIPTION
**Pull request by benjaoming**
CC: @ftao @jamalex @indirectlylit @fdellwing

Am wondering about the change from #47 - I ran the tests, and they are fine. Also locally on my machine. And I think this an important change for machines that have a non-English locale. I just don't have a Windows box to test it on.

Any concerns about releasing this?

### CODE REVIEW

**Comment by indirectlylit** [comment]
For Kolibri we'd definitely want to test on Windows before deploying the update. Upgrading in `develop` and waiting for integration tests in 0.14 would be acceptable for us – any issues ought to come out then. Can't speak for other users though.

**Comment by fdellwing** [comment]
As we are using a common and well tested python method here and not an ugly hack, this will most likely change nothing on windows at all. But I would feel better if some windows project using this, evaluates it first.

**Comment by benjaoming** [comment]
I propose that we do a 0.21b1 and try it out in a build of Kolibri..

**Comment by fdellwing** [comment]
Did you forget to publish the beta release?

**Comment by benjaoming** [comment]
@fdellwing was working from a train :) 0.21b1 released now

**Pull request merged**
